### ISSUE TITLE
Germany API questions

### ISSUE THREAD

**Issue by DBurkert** [fiskaltrust/interface-doc#118]
1 - Regarding the fields in the API, can you confirm what you mean by “mandatory if applicable/if available?  I assume if we don’t use these fields, they are not mandatory.

2 - Product barcode.  If that our software’s product ID, or a universal product code (UPC)?

3 - How can we request a technical session with our developer?

**Comment by TSchmiedlechner** [comment]
Hi @DBurkert,
first of all: sorry for not responding earlier. I was 100% convinced that I already answered this issue, but it seems like I forgot to send the comment.

Regarding your questions:
1. You're right. If the fields are not used by your POS system, there's no need to send them (unless otherwise specified in the description of the field).
2. The ProductBarcode is meant to contain the GTIN - therefore, if your scenario uses UPC, that's the value you should send there, yes.
3. If you haven't already done so, please reach out to support@fiskaltrust.de

Again, sorry for the late response.
Tom
