### ISSUE TITLE
DE: out of operation receipt/Stop receipt disables all Queues

### ISSUE THREAD

**Issue by rgenz** [fiskaltrust/interface-doc#132]
I configured a Cashbox with 3 Queues (POS terminals); initial operation receipt runs fine for all Queues as well as all following requests.
"Out off operation receipt" (0x4445 0001 0000 0004) called for one queue; this finished without error; doing a zero-receipt for this Queue afterwards reports an error - fine.
Calling a zero receipt on the other 2 Queues reports SCU not active -why ?
In the portal the SCU is no loger reported as active - why ?
I set up a new Queue - Initial Operation request for the new queue failes - why ?

Tried with Swissbit & Fiskaly SCU; tried with all versions from middleware 1.3.3 up to 1.3.10.

**Comment by TSchmiedlechner** [comment]
Hi @rgenz,
Thanks for the excellent question. This behavior is indeed expected, as we tried to align the "default" actions to the most common scenarios. However, you can easily work around this by adding the ftReceiptCaseFlag `0x0000000001000000` to the out-of-operation receipt:

![image](https://user-images.githubusercontent.com/7840981/99502523-79708480-297d-11eb-9d1e-7f683b22f1b5.png)
(Screenshot from our [docs](https://docs.fiskaltrust.cloud/doc/interface-doc/doc/appendix-de-kassensichv/reference-tables/type-of-receipt-ftreceiptcase.html#ftreceiptcaseflag))

This should prevent the state change in the TSE.

**Comment by Silvern29** [comment]
The documentation for the ftreceiptcase "0x4445000000000004 - out of operation receipt / stop-receipt" seems to say otherwise:

"It is disabling the fiskaltrust.SecurityMechanism including the deactivation of the client ID used in the TSE for the current queue. Optionally one can also deactivate the complete TSE used in background. This option will be available by a using a special flag soon."

How can a disabled Swissbit Hardware TSE be activated again on the same client with another queue?

**Comment by TSchmiedlechner** [comment]
Hi, sorry for the late response and the inconvenience caused by this ambiguity in our docs. We rewrote this paragraph so that it should now be clear that the default-behavior disables the TSE.

I think that this topic was already clarified via a support ticket (I saw a related one); but just in case, and for future reference:
It's possible to factory reset the development versions of the Swissbit TSE with the `wormCLI.exe` tool that is placed on the USB drive the TSE emulates; it should be called like this:
```cmd
wormCLI.exe <drive-letter> tseFactoryReset
```

Again, sorry for the inconvenience. I hope this helps.

**Comment by rgenz** [comment]
Vielen Dank ☺

Gesendet von meinem Fujitsu LIFEBOOK U757

Mit freundlichen Grüßen
Ralf Genz
Dipl.-Ing., Projektmanager
FJ CE EPS Application Services
[cid:image004.gif@01CEE08A.195DCF10]
FUJITSU
Hindenburgstrasse 49, 22297 Hamburg, Deutschland
Tel.: +49 (40) 51203 187
Mob.: +49 (173) 654 41 43
Fax: +49 (40) 51203 279
E-mail: Ralf.Genz@fujitsu.com<mailto:Ralf.Genz@fujitsu.com>
Web: ts.fujitsu.com<http://ts.fujitsu.com/>
This communication contains information that is confidential, proprietary in nature and/or privileged.  It is for the exclusive use of the intended recipient(s). If you are not the intended recipient(s) or the person responsible for delivering it to the intended recipient(s), please note that any form of dissemination, distribution or copying of this communication is strictly prohibited and may be unlawful. If you have received this communication in error, please immediately notify the sender and delete the original communication. Thank you for your cooperation.
Please be advised that neither Fujitsu, its affiliates, its employees or agents accept liability for any errors, omissions or damages caused by delays of receipt or by any virus infection in this message or its attachments, or which may otherwise arise as a result of this e-mail transmission.
