### ISSUE TITLE
Exception when initialising Swissbit-TSE

### ISSUE THREAD

**Issue by Silvern29** [fiskaltrust/interface-doc#215]
When trying to initialise a customers Swissbit-TSE the following exception occurs:

2021-11-05 11:40:45.872 +01:00 [ERR] Failed to execute SetTseStateAsync
fiskaltrust.Middleware.SCU.DE.Swissbit.Interop.Exceptions.SwissbitException: Invalid Response from TSE. 
   bei fiskaltrust.Middleware.SCU.DE.Swissbit.Interop.Helpers.SwissbitExceptionHelper.ThrowIfError(WormError error)
   bei fiskaltrust.Middleware.SCU.DE.Swissbit.Interop.SwissbitProxy.<>c__DisplayClass22_0.<TseSetupAsync>b__0()
   bei fiskaltrust.Middleware.SCU.DE.SwissbitBase.Helpers.LockingHelper.<PerformWithLock>d__6.MoveNext()

**Comment by fiscoal** [comment]
It would seem as if the SCU did not receive a proper answer from the TSE.

    [ERR] Failed to execute SetTseStateAsync

This often happens when the device was sleeping earlier (_power-saving modes should be generally disabled for machines with a TSE connected_) or when any low-level file-scanning services (virus scanner, **including** Microsoft Defender) interfere with the communication. Another reason could be the way the TSE is attached, it should be directly connected to the USB ports without any hubs or similar in-between. The same goes for virtualised setups, fiskaltrust.Middleware should be running on metal.

But it would be best to clarify this with the German Customer Success team via a support ticket. Please just drop them a message at `support@fiskaltrust.de`. Thanks.

**Comment by Silvern29** [comment]
Thank you for your help. I didn't realise the middleware was running on a virtualised setup. Our customer will now put a dongle server in between. I think this will help.

**Comment by fiscoal** [comment]
No worries, my pleasure.

The bottom line, or what it essentially comes down to, is that the communication between fiskaltrust.Middleware and the TSE device needs to be as "direct" and unhindered as possible. USB hubs and file scanners can interfere with the communication, as can tunneled-through USB commands in a virtualised setup, such as yours.

If that dongle server allows for standard USB commands, it should probably work fine, but should you still experience issues, please try to "move" the device physically and logically as close as possible to the Middleware setup.
